const { PrismaClient } = require('@prisma/client')
const prisma = new PrismaClient()

// ====== HOTELS DATA (mapped to schema: name, description, address, city, rating, stars, imageUrl, amenities) ======
const HOTELS = {
  Mumbai: [
    { name: 'Taj Mahal Palace', stars: 5, rating: 4.9, description: 'An iconic landmark since 1903, the Taj Mahal Palace overlooks the Gateway of India. This legendary hotel blends Moorish, Oriental and Florentine styles with world-class luxury.', address: 'Apollo Bunder, Colaba, Mumbai 400001', imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200', amenities: 'Pool,Spa,WiFi,Restaurant,Bar,Gym,Concierge', rooms: [{ type: 'Palace Suite', price: 35000, capacity: 2 }, { type: 'Luxury Room', price: 25000, capacity: 2 }, { type: 'Superior Room', price: 18000, capacity: 2 }] },
    { name: 'The Oberoi Mumbai', stars: 5, rating: 4.8, description: 'Perched on Marine Drive with stunning Arabian Sea views, The Oberoi Mumbai is a masterpiece of contemporary luxury and personalized service.', address: 'Nariman Point, Mumbai 400021', imageUrl: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=1200', amenities: 'Pool,Spa,WiFi,Restaurant,Bar,Butler', rooms: [{ type: 'Kohinoor Suite', price: 30000, capacity: 2 }, { type: 'Deluxe Sea View', price: 22000, capacity: 2 }] },
    { name: 'Four Seasons Mumbai', stars: 5, rating: 4.8, description: 'Rising 34 stories above the city, Four Seasons Hotel Mumbai offers panoramic views of the Arabian Sea and the city skyline.', address: 'Dr E Moses Road, Worli, Mumbai 400018', imageUrl: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=1200', amenities: 'Pool,Spa,WiFi,Restaurant,Bar,Gym', rooms: [{ type: 'Presidential Suite', price: 35000, capacity: 2 }, { type: 'Premier Room', price: 23000, capacity: 2 }] },
    { name: 'JW Marriott Juhu', stars: 5, rating: 4.7, description: 'Located steps from Juhu Beach, JW Marriott offers beachfront luxury with spectacular sunset views over the Arabian Sea.', address: 'Juhu Tara Road, Juhu, Mumbai 400049', imageUrl: 'https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=1200', amenities: 'Pool,Spa,WiFi,Restaurant,Beach Access', rooms: [{ type: 'Ocean Suite', price: 28000, capacity: 2 }, { type: 'Deluxe Room', price: 20000, capacity: 2 }] },
    { name: 'The Leela Mumbai', stars: 5, rating: 4.7, description: 'A world of unmatched luxury and comfort near Chhatrapati Shivaji International Airport.', address: 'Sahar, Andheri East, Mumbai 400059', imageUrl: 'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=1200', amenities: 'Pool,Spa,WiFi,Restaurant,Business Center', rooms: [{ type: 'Royal Suite', price: 26000, capacity: 2 }, { type: 'Club Room', price: 19000, capacity: 2 }] },
    { name: 'Trident Nariman Point', stars: 5, rating: 4.6, description: 'Elegant hotel at the epicenter of Mumbai business district with spectacular sea views.', address: 'Nariman Point, Mumbai 400021', imageUrl: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=1200', amenities: 'Pool,WiFi,Restaurant,Bar', rooms: [{ type: 'Sea View Suite', price: 22000, capacity: 2 }, { type: 'Deluxe Room', price: 16000, capacity: 2 }] },
    { name: 'Sofitel Mumbai BKC', stars: 5, rating: 4.6, description: 'French art de vivre meets Indian hospitality at this elegant business hotel in BKC.', address: 'C-57, G Block, Bandra Kurla Complex, Mumbai', imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200', amenities: 'Pool,Spa,WiFi,Restaurant', rooms: [{ type: 'Opera Suite', price: 22000, capacity: 2 }, { type: 'Superior Room', price: 15000, capacity: 2 }] },
    { name: 'Grand Hyatt Mumbai', stars: 5, rating: 4.5, description: 'Contemporary luxury hotel with Mumbai\'s largest hotel pool and award-winning restaurants.', address: 'Off Western Express Highway, Santa Cruz East', imageUrl: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=1200', amenities: 'Pool,Spa,WiFi,Restaurant,Gym', rooms: [{ type: 'Grand Suite', price: 24000, capacity: 2 }, { type: 'Club Room', price: 17000, capacity: 2 }] },
    { name: 'ITC Grand Central Mumbai', stars: 5, rating: 4.5, description: 'A grand luxury hotel in the heart of Mumbai with Responsible Luxury philosophy.', address: 'Dr Babasaheb Ambedkar Road, Parel, Mumbai', imageUrl: 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=1200', amenities: 'Pool,Spa,WiFi,Restaurant,Wellness', rooms: [{ type: 'ITC One Suite', price: 25000, capacity: 2 }, { type: 'Executive Room', price: 18000, capacity: 2 }] },
    { name: 'Novotel Mumbai Juhu', stars: 4, rating: 4.3, description: 'Contemporary hotel offering comfort and style steps from the iconic Juhu Beach.', address: 'Balraj Sahani Marg, Juhu, Mumbai 400049', imageUrl: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=1200', amenities: 'Pool,WiFi,Restaurant,Kids Club', rooms: [{ type: 'Suite', price: 14000, capacity: 2 }, { type: 'Standard Room', price: 10000, capacity: 2 }] },
  ],
  Delhi: [
    { name: 'The Imperial New Delhi', stars: 5, rating: 4.9, description: 'Built in 1931, The Imperial is a stunning example of colonial architecture, offering a unique window into Indian heritage and luxury.', address: 'Janpath, New Delhi 110001', imageUrl: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=1200', amenities: 'Pool,Spa,WiFi,Restaurant,Art Gallery', rooms: [{ type: 'Heritage Suite', price: 38000, capacity: 2 }, { type: 'Deluxe Room', price: 28000, capacity: 2 }] },
    { name: 'Taj Mahal Hotel Delhi', stars: 5, rating: 4.8, description: 'Located in the heart of Lutyens\' Delhi, this iconic hotel is a stone\'s throw from India Gate.', address: '1 Mansingh Road, New Delhi 110011', imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200', amenities: 'Pool,Spa,WiFi,Restaurant,Bar', rooms: [{ type: 'Tata Suite', price: 35000, capacity: 2 }, { type: 'Luxury Room', price: 24000, capacity: 2 }] },
    { name: 'The Leela Palace Delhi', stars: 5, rating: 4.9, description: 'The most lavish address in Delhi, The Leela Palace embodies classical Indian grandeur with modern luxury.', address: 'Africa Avenue, Chanakyapuri, New Delhi', imageUrl: 'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=1200', amenities: 'Pool,Spa,WiFi,Restaurant,Butler,Rolls Royce', rooms: [{ type: 'Royal Suite', price: 45000, capacity: 2 }, { type: 'Premier Room', price: 30000, capacity: 2 }, { type: 'Deluxe Room', price: 22000, capacity: 2 }] },
    { name: 'ITC Maurya Delhi', stars: 5, rating: 4.8, description: 'Home to the legendary Bukhara restaurant, ITC Maurya is where world leaders stay in Delhi.', address: 'Sardar Patel Marg, Diplomatic Enclave, Delhi', imageUrl: 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=1200', amenities: 'Pool,Spa,WiFi,Bukhara,Dum Pukht', rooms: [{ type: 'ITC One Suite', price: 32000, capacity: 2 }, { type: 'Towers Room', price: 22000, capacity: 2 }] },
    { name: 'Oberoi New Delhi', stars: 5, rating: 4.8, description: 'Overlooking the Delhi Golf Course, The Oberoi New Delhi is a sanctuary of understated luxury.', address: 'Dr. Zakir Hussain Marg, New Delhi 110003', imageUrl: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=1200', amenities: 'Pool,Spa,WiFi,Restaurant,Golf Course View', rooms: [{ type: 'Kohinoor Suite', price: 38000, capacity: 2 }, { type: 'Premier Room', price: 26000, capacity: 2 }] },
    { name: 'Shangri-La Delhi', stars: 5, rating: 4.7, description: 'Inspired by the legendary mystical Shangri-La, this hotel offers Asian hospitality at its finest.', address: '19 Ashoka Road, Connaught Place, New Delhi', imageUrl: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=1200', amenities: 'Pool,Spa,WiFi,Restaurant,Club Lounge', rooms: [{ type: 'Horizon Suite', price: 28000, capacity: 2 }, { type: 'Deluxe Room', price: 20000, capacity: 2 }] },
    { name: 'Hyatt Regency Delhi', stars: 5, rating: 4.6, description: 'A landmark hotel in Delhi offering contemporary luxury and world-class amenities.', address: 'Bhikaiji Cama Place, New Delhi 110066', imageUrl: 'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=800', amenities: 'Pool,Spa,WiFi,Restaurant,Business Center', rooms: [{ type: 'Regency Suite', price: 22000, capacity: 2 }, { type: 'Standard Room', price: 16000, capacity: 2 }] },
    { name: 'Andaz Delhi', stars: 5, rating: 4.6, description: 'A vibrant lifestyle hotel celebrating local Delhi culture at Aerocity.', address: 'Asset No. 1, Aerocity, New Delhi 110037', imageUrl: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=1200', amenities: 'Pool,Spa,WiFi,Restaurant,Art Collection', rooms: [{ type: 'Andaz Suite', price: 26000, capacity: 2 }, { type: 'Luxe Room', price: 18000, capacity: 2 }] },
    { name: 'Park Hyatt Delhi', stars: 5, rating: 4.7, description: 'Sophisticated urban retreat offering contemporary luxury in Gurugram.', address: 'Sector 17B, Gurugram, Delhi NCR', imageUrl: 'https://images.unsplash.com/photo-1584132967334-10e028bd69f7?w=1200', amenities: 'Pool,Spa,WiFi,Restaurant', rooms: [{ type: 'Park Suite', price: 30000, capacity: 2 }, { type: 'Deluxe Room', price: 21000, capacity: 2 }] },
    { name: 'Radisson Blu Delhi', stars: 4, rating: 4.4, description: 'Convenient luxury hotel minutes from Indira Gandhi International Airport.', address: 'National Highway 8, Mahipalpur, New Delhi', imageUrl: 'https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=1200', amenities: 'Pool,WiFi,Restaurant,Airport Shuttle', rooms: [{ type: 'Business Suite', price: 16000, capacity: 2 }, { type: 'Standard Room', price: 12000, capacity: 2 }] },
  ],
  Goa: [
    { name: 'Taj Exotica Goa', stars: 5, rating: 4.9, description: 'A sprawling 56-acre resort on Goa\'s most beautiful beach, Taj Exotica is the ultimate tropical luxury escape.', address: 'Calwaddo, Benaulim, Salcete, South Goa', imageUrl: 'https://images.unsplash.com/photo-1540541338287-41700207dee6?w=1200', amenities: 'Private Beach,Pool,Spa,WiFi,Watersports', rooms: [{ type: 'Villa Suite', price: 45000, capacity: 2 }, { type: 'Premium Room', price: 35000, capacity: 2 }] },
    { name: 'W Goa', stars: 5, rating: 4.8, description: 'Perched dramatically above Vagator Beach, W Goa is where living and nightlife blend with luxury.', address: 'Vagator Beach, Bardez, North Goa', imageUrl: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=1200', amenities: 'Infinity Pool,Spa,WiFi,Beach Club,Nightlife', rooms: [{ type: 'Marvelous Suite', price: 38000, capacity: 2 }, { type: 'Wonderful Room', price: 30000, capacity: 2 }] },
    { name: 'Alila Diwa Goa', stars: 5, rating: 4.8, description: 'Nestled amidst lush paddy fields, Alila Diwa captures the spirit of timeless Goa.', address: 'Adao Waddo, Majorda, Salcete, South Goa', imageUrl: 'https://images.unsplash.com/photo-1540541338287-41700207dee6?w=1200', amenities: 'Pool,Spa,WiFi,Ayurveda,Beach Access', rooms: [{ type: 'Diwa Suite', price: 36000, capacity: 2 }, { type: 'Terrace Room', price: 28000, capacity: 2 }] },
    { name: 'Park Hyatt Goa', stars: 5, rating: 4.7, description: 'A Mediterranean-inspired resort on the pristine Arossim Beach in South Goa.', address: 'Arossim Beach, Cansaulim, South Goa', imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200', amenities: 'Beach,Pool,Spa,WiFi,Watersports', rooms: [{ type: 'Park Suite', price: 34000, capacity: 2 }, { type: 'Park Room', price: 26000, capacity: 2 }] },
    { name: 'The Leela Goa', stars: 5, rating: 4.8, description: 'Set between the Sal River and the Arabian Sea, The Leela Goa is a paradise of luxury and nature.', address: 'Mobor, Cavelossim, Salcete, Goa 403731', imageUrl: 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=1200', amenities: 'Private Beach,Pool,Spa,Golf,Watersports', rooms: [{ type: 'Royal Villa', price: 42000, capacity: 2 }, { type: 'Lagoon Suite', price: 32000, capacity: 2 }] },
    { name: 'Taj Fort Aguada', stars: 5, rating: 4.7, description: 'Built around a 16th century Portuguese fort, Taj Fort Aguada is a unique heritage resort.', address: 'Sinquerim, Candolim, Bardez, North Goa', imageUrl: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=1200', amenities: 'Beach,Pool,Spa,WiFi,Heritage Fort', rooms: [{ type: 'Fort Suite', price: 30000, capacity: 2 }, { type: 'Sea View Room', price: 22000, capacity: 2 }] },
    { name: 'Vivanta Goa', stars: 5, rating: 4.6, description: 'Contemporary luxury hotel with stunning views of the Mandovi River and Arabian Sea.', address: 'Panaji - Miramar - Dona Paula Road, Goa', imageUrl: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=1200', amenities: 'Pool,Spa,WiFi,Beach Access', rooms: [{ type: 'Premium Suite', price: 24000, capacity: 2 }, { type: 'Deluxe Room', price: 18000, capacity: 2 }] },
    { name: 'Novotel Goa Resort', stars: 4, rating: 4.4, description: 'Modern resort offering comfortable luxury in the heart of North Goa.', address: 'Candolim, Bardez, North Goa 403515', imageUrl: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=1200', amenities: 'Pool,WiFi,Restaurant,Beach Nearby', rooms: [{ type: 'Suite', price: 18000, capacity: 2 }, { type: 'Standard Room', price: 14000, capacity: 2 }] },
    { name: 'Azaya Beach Resort', stars: 4, rating: 4.5, description: 'Boutique beach resort with Portuguese charm and tropical luxury.', address: 'House 2/166 A, Baga, North Goa', imageUrl: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=1200', amenities: 'Pool,WiFi,Restaurant,Beach', rooms: [{ type: 'Pool Suite', price: 22000, capacity: 2 }, { type: 'Deluxe Room', price: 16000, capacity: 2 }] },
    { name: 'Cidade de Goa', stars: 4, rating: 4.3, description: 'Award-winning heritage resort modeled on a traditional Goan village.', address: 'Vainguinim Beach, Dona Paula, Goa 403004', imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200', amenities: 'Beach,Pool,WiFi,Restaurant', rooms: [{ type: 'Heritage Suite', price: 16000, capacity: 2 }, { type: 'Superior Room', price: 12000, capacity: 2 }] },
  ],
  Jaipur: [
    { name: 'Rambagh Palace', stars: 5, rating: 4.9, description: 'Once the residence of the Maharaja of Jaipur, Rambagh Palace is the jewel of Jaipur — a majestic royal experience.', address: 'Bhawani Singh Road, Jaipur 302005', imageUrl: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?w=1200', amenities: 'Pool,Spa,WiFi,Restaurant,Polo,Gardens', rooms: [{ type: 'Royal Suite', price: 65000, capacity: 2 }, { type: 'Palace Room', price: 45000, capacity: 2 }, { type: 'Luxury Room', price: 32000, capacity: 2 }] },
    { name: 'Taj Jai Mahal Palace', stars: 5, rating: 4.8, description: 'A heritage palace hotel set in 18 acres of Mughal gardens in the Pink City.', address: 'Jacob Road, Civil Lines, Jaipur 302006', imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200', amenities: 'Pool,Spa,WiFi,Restaurant,Gardens', rooms: [{ type: 'Heritage Suite', price: 42000, capacity: 2 }, { type: 'Luxury Room', price: 32000, capacity: 2 }] },
    { name: 'Samode Palace', stars: 5, rating: 4.9, description: '475-year-old royal palace hotel with breathtaking frescoes and opulent royal suites.', address: 'Village Samode, Tehsil Chomu, Jaipur', imageUrl: 'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=1200', amenities: 'Pool,Spa,WiFi,Royal Dining,Heritage Walks', rooms: [{ type: 'Maharaja Suite', price: 55000, capacity: 2 }, { type: 'Royal Room', price: 40000, capacity: 2 }] },
    { name: 'Oberoi Rajvilas', stars: 5, rating: 4.9, description: 'Built around a 250-year-old Shiva temple, Oberoi Rajvilas offers the quintessential royal Rajasthan experience.', address: 'Goner Road, Jaipur 302031', imageUrl: 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=1200', amenities: 'Pool,Spa,WiFi,Royal Tents,Elephant Rides', rooms: [{ type: 'Kohinoor Tent', price: 70000, capacity: 2 }, { type: 'Premier Room', price: 50000, capacity: 2 }] },
    { name: 'ITC Rajputana', stars: 5, rating: 4.7, description: 'Inspired by Rajputana architecture, ITC Rajputana blends royal heritage with modern luxury.', address: 'Palace Road, Jaipur 302006', imageUrl: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=1200', amenities: 'Pool,Spa,WiFi,Restaurant,Business Center', rooms: [{ type: 'ITC One Suite', price: 28000, capacity: 2 }, { type: 'Executive Room', price: 20000, capacity: 2 }] },
    { name: 'Fairmont Jaipur', stars: 5, rating: 4.8, description: 'A majestic palace-inspired luxury resort with the largest hotel pool in Rajasthan.', address: 'Riico Residential Area, Kukas, Jaipur', imageUrl: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=1200', amenities: 'Pool,Spa,WiFi,Restaurant,Elephant Sanctuary', rooms: [{ type: 'Fairmont Suite', price: 38000, capacity: 2 }, { type: 'Deluxe Room', price: 28000, capacity: 2 }] },
    { name: 'Dera Mandawa', stars: 4, rating: 4.6, description: 'A beautifully restored heritage haveli in the heart of Jaipur.', address: 'Sansar Chandra Road, Jaipur 302001', imageUrl: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=1200', amenities: 'Pool,WiFi,Heritage Restaurant,Camel Rides', rooms: [{ type: 'Haveli Suite', price: 18000, capacity: 2 }, { type: 'Heritage Room', price: 15000, capacity: 2 }] },
    { name: 'Trident Jaipur', stars: 5, rating: 4.5, description: 'Set amidst Aravalli Hills with views of Amber Fort, offering authentic Rajasthani luxury.', address: 'Amber Fort Road, Khasa, Jaipur', imageUrl: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=1200', amenities: 'Pool,WiFi,Restaurant,Spa', rooms: [{ type: 'Trident Suite', price: 20000, capacity: 2 }, { type: 'Premium Room', price: 14000, capacity: 2 }] },
    { name: 'Alsisar Haveli', stars: 4, rating: 4.5, description: 'A 130-year-old restored heritage haveli offering authentic royal Rajasthani hospitality.', address: 'Sansar Chandra Road, Jaipur 302001', imageUrl: 'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=800', amenities: 'Pool,WiFi,Restaurant,Heritage Tours', rooms: [{ type: 'Maharani Suite', price: 14000, capacity: 2 }, { type: 'Haveli Room', price: 10000, capacity: 2 }] },
    { name: 'Holiday Inn Jaipur', stars: 4, rating: 4.3, description: 'Modern comfort hotel in central Jaipur with easy access to all major attractions.', address: 'Lal Kothi, Tonk Road, Jaipur 302015', imageUrl: 'https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=1200', amenities: 'Pool,WiFi,Restaurant,Business Center', rooms: [{ type: 'Suite', price: 12000, capacity: 2 }, { type: 'Standard Room', price: 8000, capacity: 2 }] },
  ],
}

// ====== RESTAURANTS DATA (mapped to schema: name, cuisine, description, address, city, rating, priceRange, imageUrl, capacity, openTime, closeTime) ======
const RESTAURANTS = {
  Mumbai: [
    { name: 'Wasabi by Morimoto', cuisine: 'Japanese', rating: 4.8, priceRange: '₹₹₹₹', description: 'Iron Chef Masaharu Morimoto brings authentic Japanese cuisine to Mumbai\'s finest hotel.', address: 'Taj Mahal Palace Hotel, Colaba, Mumbai', imageUrl: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=1200', capacity: 40, openTime: '12:30', closeTime: '23:45' },
    { name: 'Trishna', cuisine: 'Coastal Seafood', rating: 4.8, priceRange: '₹₹₹', description: 'Since 1981, Trishna has been Mumbai\'s most celebrated seafood destination with legendary butter garlic crab.', address: '7 Sai Baba Marg, Kala Ghoda, Fort, Mumbai', imageUrl: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=1200', capacity: 60, openTime: '12:00', closeTime: '23:45' },
    { name: 'Bombay Canteen', cuisine: 'Modern Indian', rating: 4.7, priceRange: '₹₹₹', description: 'A love letter to India\'s regional cuisines, reimagined by Chef Thomas Zacharias.', address: 'Process House, Kamala Mills Compound, Mumbai', imageUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=1200', capacity: 80, openTime: '12:00', closeTime: '01:00' },
    { name: 'The Table', cuisine: 'European Farm-to-Table', rating: 4.7, priceRange: '₹₹₹₹', description: 'Celebrated farm-to-table European restaurant with a globally inspired menu.', address: '12 Apollo Bunder, Colaba, Mumbai 400001', imageUrl: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=1200', capacity: 55, openTime: '12:30', closeTime: '23:00' },
    { name: 'Khyber', cuisine: 'North Indian Mughlai', rating: 4.6, priceRange: '₹₹₹', description: 'An institution since 1958, Khyber serves legendary North Indian cuisine in a palatial setting.', address: '145 Mahatma Gandhi Road, Kala Ghoda, Mumbai', imageUrl: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=1200', capacity: 70, openTime: '12:30', closeTime: '23:30' },
    { name: 'Bastian', cuisine: 'Seafood & Grill', rating: 4.6, priceRange: '₹₹₹', description: 'Trendy seafood restaurant in Bandra known for its fresh catches and lively atmosphere.', address: 'Linking Road, Bandra West, Mumbai 400050', imageUrl: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=1200', capacity: 65, openTime: '12:30', closeTime: '00:00' },
    { name: 'Peshwari', cuisine: 'North West Frontier', rating: 4.6, priceRange: '₹₹₹', description: 'Authentic North West Frontier cuisine with tandoor specialties in a rustic setting.', address: 'ITC Grand Central, Dr Babasaheb Ambedkar Road', imageUrl: 'https://images.unsplash.com/photo-1552566626-52f8b828329f?w=1200', capacity: 50, openTime: '19:00', closeTime: '23:45' },
    { name: 'Cafe Mondegar', cuisine: 'Goan Continental', rating: 4.4, priceRange: '₹₹', description: 'Colaba\'s most beloved cafe since 1932, famous for its Mario Miranda murals and cold beer.', address: '5A Metro House, Colaba Causeway, Mumbai', imageUrl: 'https://images.unsplash.com/photo-1424847651672-bf20a4b0982b?w=1200', capacity: 45, openTime: '07:30', closeTime: '23:30' },
    { name: 'Neel Restaurant', cuisine: 'Contemporary Indian', rating: 4.5, priceRange: '₹₹₹', description: 'Fine dining overlooking the Mahalaxmi Racecourse with inventive Indian cuisine.', address: 'Tote on the Turf, Mahalaxmi Racecourse', imageUrl: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?w=1200', capacity: 50, openTime: '12:30', closeTime: '23:30' },
    { name: 'Jamjar Diner', cuisine: 'American Comfort', rating: 4.5, priceRange: '₹₹', description: 'Beloved all-day diner famous for milkshakes, burgers and loaded sandwiches.', address: 'Versova, Andheri West, Mumbai', imageUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=1200', capacity: 40, openTime: '11:00', closeTime: '23:30' },
  ],
}

async function main() {
  console.log('🌱 Starting India seed — 40 hotels + 10 restaurants...\n')

  // Clean existing rooms to avoid duplicates
  await prisma.room.deleteMany({})
  await prisma.hotel.deleteMany({})
  await prisma.restaurant.deleteMany({})
  console.log('🗑️  Cleared existing data\n')

  let hotelCount = 0, roomCount = 0, restaurantCount = 0

  for (const [city, cityHotels] of Object.entries(HOTELS)) {
    console.log(`\n🏙️  ${city}:`)
    for (const hotelData of cityHotels) {
      const { rooms, ...hotel } = hotelData
      const created = await prisma.hotel.create({ data: { ...hotel, city } })
      console.log(`  ✅ ${created.name}`)
      hotelCount++

      for (const room of rooms) {
        await prisma.room.create({ data: { ...room, hotelId: created.id, imageUrl: hotel.imageUrl } })
        console.log(`     🛏️  ${room.type} — ₹${room.price.toLocaleString()}`)
        roomCount++
      }
    }
  }

  for (const [city, cityRestaurants] of Object.entries(RESTAURANTS)) {
    console.log(`\n🍽️  ${city} Restaurants:`)
    for (const restaurant of cityRestaurants) {
      const created = await prisma.restaurant.create({ data: { ...restaurant, city } })
      console.log(`  ✅ ${created.name} (${created.cuisine})`)
      restaurantCount++
    }
  }

  console.log(`\n🎉 DONE! Seeded ${hotelCount} hotels, ${roomCount} rooms, ${restaurantCount} restaurants across ${Object.keys(HOTELS).length} cities!`)
}

main().catch(console.error).finally(() => prisma.$disconnect())
